name: yibu_conda
channels:
  - defaults
dependencies:
  - ca-certificates=2020.7.22=0
  - certifi=2020.6.20=py38_0
  - click=7.1.2=py_0
  - flask=1.1.2=py_0
  - itsdangerous=1.1.0=py_0
  - jinja2=2.11.2=py_0
  - libcxx=10.0.0=1
  - libedit=3.1.20191231=h1de35cc_1
  - libffi=3.3=hb1e8313_2
  - markupsafe=1.1.1=py38h1de35cc_1
  - ncurses=6.2=h0a44026_1
  - openssl=1.1.1g=h1de35cc_0
  - pip=20.2.2=py38_0
  - python=3.8.5=h26836e1_1
  - readline=8.0=h1de35cc_0
  - setuptools=49.6.0=py38_0
  - sqlite=3.33.0=hffcf06c_0
  - tk=8.6.10=hb0a8c7a_0
  - werkzeug=1.0.1=py_0
  - wheel=0.35.1=py_0
  - xz=5.2.5=h1de35cc_0
  - zlib=1.2.11=h1de35cc_3
  - pip:
    - beautifulsoup4==4.9.1
    - cachelib==0.1.1
    - chardet==3.0.4
    - flask-cors==3.0.9
    - gunicorn==20.0.4
    - httplib2==0.18.1
    - idna==2.10
    - lxml==4.5.2
    - python-dotenv==0.14.0
    - requests==2.24.0
    - six==1.15.0
    - soupsieve==2.0.1
    - urllib3==1.25.10
prefix: /opt/anaconda3/envs/yibu_conda

